/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iHome;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ovin Hansaja
 */
public class Community extends javax.swing.JFrame {

    /**
     * Creates new form Community
     */
    public Community() {
        initComponents();
        Connect();
        load();
    } 
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel df;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ihome","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void load()
    {
        int a;
        
        try {
            pst = con.prepareStatement("select * from members");
            rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel)tbl_members.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1; i<=a; i++)
                {
                    v2.add(rs.getString("MemberID"));
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("NIC"));
                    v2.add(rs.getString("Address"));
                    v2.add(rs.getString("Contact"));
                    v2.add(rs.getString("Email"));
                    v2.add(rs.getString("Date"));
                }
                df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_community = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_stock = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        btn_delivery = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_supply = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_cls = new javax.swing.JLabel();
        btn_min = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_nic = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_contact = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_del = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_members = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_community.setBackground(new java.awt.Color(204, 204, 204));
        btn_community.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_community.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_communityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_communityMouseExited(evt);
            }
        });
        btn_community.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/community.png"))); // NOI18N
        btn_community.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel6.setText("COMMUNITY");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_community.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_community, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 50));

        btn_stock.setBackground(new java.awt.Color(153, 153, 153));
        btn_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_stockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_stockMouseExited(evt);
            }
        });
        btn_stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/stock.png"))); // NOI18N
        btn_stock.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel1.setText("STOCK");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_stock.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/iHome-Logo 200x200.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Century", 2, 18)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, 20));

        btn_delivery.setBackground(new java.awt.Color(153, 153, 153));
        btn_delivery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deliveryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deliveryMouseExited(evt);
            }
        });
        btn_delivery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/delivered.png"))); // NOI18N
        btn_delivery.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel10.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel10.setText("DELIVERY");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_delivery.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        btn_supply.setBackground(new java.awt.Color(153, 153, 153));
        btn_supply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_supply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supplyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supplyMouseExited(evt);
            }
        });
        btn_supply.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/Supply.png"))); // NOI18N
        btn_supply.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel5.setText("SUPPLY");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_supply.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_supply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cls.setBackground(new java.awt.Color(255, 255, 255));
        btn_cls.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cls.setText("x");
        btn_cls.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_cls.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_cls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clsMousePressed(evt);
            }
        });
        jPanel4.add(btn_cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 20));

        btn_min.setBackground(new java.awt.Color(51, 51, 51));
        btn_min.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_min.setText("-");
        btn_min.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_minMousePressed(evt);
            }
        });
        jPanel4.add(btn_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 30, 20));

        jLabel7.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 20)); // NOI18N
        jLabel7.setText("The best iPhone collection...");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 250, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("NIC No");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Address");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Contact No");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel19.setText("Register Member");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel20.setText("Email");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("Name");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        btn_reg.setBackground(new java.awt.Color(153, 153, 153));
        btn_reg.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_reg.setText("Register");
        btn_reg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_regMouseExited(evt);
            }
        });
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 100, -1));

        txt_email.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 220, -1));

        txt_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, -1));

        txt_nic.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 220, -1));

        txt_address.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 220, -1));

        txt_contact.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPanel1.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 220, -1));

        lbl_name.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 0, 0));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 220, 12));

        lbl_email.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(255, 0, 0));
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 220, 12));

        lbl_nic.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_nic.setForeground(new java.awt.Color(255, 0, 0));
        lbl_nic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(lbl_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 220, 12));

        lbl_address.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_address.setForeground(new java.awt.Color(255, 0, 0));
        lbl_address.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(lbl_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 220, 12));

        lbl_contact.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_contact.setForeground(new java.awt.Color(255, 0, 0));
        lbl_contact.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(lbl_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 220, 12));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel11.setText("Delete Member");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        btn_del.setBackground(new java.awt.Color(153, 153, 153));
        btn_del.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_del.setText("Delete");
        btn_del.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_delMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_delMouseExited(evt);
            }
        });
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });
        jPanel5.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Select from the table");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 300, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 370));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 2));

        tbl_members.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "NIC No", "Address", "Contact No", "Email", "Date"
            }
        ));
        tbl_members.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tbl_members);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 740, 220));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 800, 280));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 800, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseEntered
        // TODO add your handling code here:
        btn_cls.setForeground(Color.white);
    }//GEN-LAST:event_btn_clsMouseEntered

    private void btn_clsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseExited
        // TODO add your handling code here:
        btn_cls.setForeground(Color.black);
    }//GEN-LAST:event_btn_clsMouseExited

    private void btn_clsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_clsMousePressed

    private void btn_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseEntered
        // TODO add your handling code here:
        btn_min.setForeground(Color.white);
    }//GEN-LAST:event_btn_minMouseEntered

    private void btn_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseExited
        // TODO add your handling code here:
        btn_min.setForeground(Color.black);
    }//GEN-LAST:event_btn_minMouseExited

    private void btn_minMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMousePressed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minMousePressed

    private void btn_delMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delMouseEntered
        // TODO add your handling code here:
        btn_del.setBackground(Color.white);
    }//GEN-LAST:event_btn_delMouseEntered

    private void btn_delMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delMouseExited
        // TODO add your handling code here:
        btn_del.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_delMouseExited

    private void btn_regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regMouseEntered
        // TODO add your handling code here:
        btn_reg.setBackground(Color.white);
    }//GEN-LAST:event_btn_regMouseEntered

    private void btn_regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regMouseExited
        // TODO add your handling code here:
        btn_reg.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_regMouseExited

    private void btn_supplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplyMouseExited
        // TODO add your handling code here:
        btn_supply.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_supplyMouseExited

    private void btn_supplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplyMouseEntered
        // TODO add your handling code here:
        btn_supply.setBackground(Color.white);
    }//GEN-LAST:event_btn_supplyMouseEntered

    private void btn_supplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplyMouseClicked
        // TODO add your handling code here:
        dispose();
        Supply supply = new Supply();
        supply.setVisible(true);
    }//GEN-LAST:event_btn_supplyMouseClicked

    private void btn_deliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deliveryMouseExited
        // TODO add your handling code here:
        btn_delivery.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_deliveryMouseExited

    private void btn_deliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deliveryMouseEntered
        // TODO add your handling code here:
        btn_delivery.setBackground(Color.white);
    }//GEN-LAST:event_btn_deliveryMouseEntered

    private void btn_deliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deliveryMouseClicked
        // TODO add your handling code here:
        dispose();
        Delivery delivery = new Delivery();
        delivery.setVisible(true);
    }//GEN-LAST:event_btn_deliveryMouseClicked

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setForeground(Color.black);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setForeground(Color.white);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_stockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseExited
        // TODO add your handling code here:
        btn_stock.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_stockMouseExited

    private void btn_stockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseEntered
        // TODO add your handling code here:
        btn_stock.setBackground(Color.white);
    }//GEN-LAST:event_btn_stockMouseEntered

    private void btn_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseClicked
        // TODO add your handling code here:
        dispose();
        Stock stock = new Stock();
        stock.setVisible(true);
    }//GEN-LAST:event_btn_stockMouseClicked

    private void btn_communityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_communityMouseExited
        // TODO add your handling code here:
        btn_community.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_communityMouseExited

    private void btn_communityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_communityMouseEntered
        // TODO add your handling code here:
        btn_community.setBackground(Color.white);
    }//GEN-LAST:event_btn_communityMouseEntered

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        try {
            // TODO add your handling code here:
            String name = txt_name.getText();
            String nic = txt_nic.getText();
            String address = txt_address.getText();
            String contact = txt_contact.getText();
            String email = txt_email.getText();
            
            if(name.equals("")){
                lbl_name.setText("Name cannot be empty");
            }
            else if(!name.matches("[a-zA-Z]+")){
                lbl_name.setText("Name cannot accept");
            }
            else{
                lbl_name.setText("");
                
                if(nic.length()!=10){
                    lbl_nic.setText("NIC No cannot be empty and should be valid");
                }
                else{
                    lbl_nic.setText("");
                    
                    if(address.equals("")){
                        lbl_address.setText("Address cannot be empty");
                    }
                    else{
                        lbl_address.setText("");
                        
                        if(contact.length()!=10){
                            lbl_contact.setText("Contact No length should be 10 digits");
                        }
                        else if(!contact.matches("^[0-9]*$")){
                            lbl_contact.setText("Contact No length should be 10 digits");
                        }
                        else{
                            lbl_contact.setText("");
                            
                            if(email.equals("")){
                                lbl_email.setText("Email cannot be empty");
                            }
                            else if(!email.matches("^(.+)@(.+)$")){
                                lbl_email.setText("Email is not valid");
                            }
                            else{
                                lbl_email.setText("");
                                
                                pst = con.prepareStatement("Insert into members(Name,NIC,Address,Contact,Email) values(?,?,?,?,?)");
                                pst.setString(1, name);
                                pst.setString(2, nic);
                                pst.setString(3, address);
                                pst.setString(4, contact);
                                pst.setString(5, email);
                                pst.executeUpdate();
                                JOptionPane.showMessageDialog(this, "Member Registered");

                                txt_name.setText("");
                                txt_nic.setText("");
                                txt_address.setText("");
                                txt_contact.setText("");
                                txt_email.setText("");
                                txt_name.requestFocus();
            
                                load();
                            }
                        }
                    }
                }
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
         // TODO add your handling code here:
         df = (DefaultTableModel)tbl_members.getModel();
         
         int  selected = tbl_members.getSelectedRow();
         
         int id = Integer.parseInt(df.getValueAt(selected, 0).toString());
         
        try {
            pst = con.prepareStatement("delete from members where MemberID = ?");
            pst.setInt(1, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Member Deleted");
            
            load();
            
        } catch (SQLException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_delActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Community.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Community.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Community.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Community.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Community().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cls;
    private javax.swing.JPanel btn_community;
    private javax.swing.JButton btn_del;
    private javax.swing.JPanel btn_delivery;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_min;
    private javax.swing.JButton btn_reg;
    private javax.swing.JPanel btn_stock;
    private javax.swing.JPanel btn_supply;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_contact;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nic;
    private javax.swing.JTable tbl_members;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    // End of variables declaration//GEN-END:variables
}
