/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iHome;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Ovin Hansaja
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Login() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_cls = new javax.swing.JLabel();
        btn_min = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        user_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_user = new javax.swing.JLabel();
        lbl_pass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Home"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/iHome-Logo 200x200.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 250));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cls.setBackground(new java.awt.Color(255, 255, 255));
        btn_cls.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cls.setText("x");
        btn_cls.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_cls.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_cls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clsMousePressed(evt);
            }
        });
        jPanel4.add(btn_cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 20));

        btn_min.setBackground(new java.awt.Color(51, 51, 51));
        btn_min.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_min.setText("-");
        btn_min.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_minMousePressed(evt);
            }
        });
        jPanel4.add(btn_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 30, 20));

        jLabel7.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 20)); // NOI18N
        jLabel7.setText("The best iPhone collection...");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 15, 250, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/pin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 24, 24));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/user.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 24, 24));

        txt_user.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txt_user.setText("Username");
        txt_user.setBorder(null);
        txt_user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_userFocusGained(evt);
            }
        });
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userMousePressed(evt);
            }
        });
        jPanel2.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 250, 24));

        user_pass.setFont(new java.awt.Font("Rockwell", 1, 20)); // NOI18N
        user_pass.setText("Password");
        user_pass.setBorder(null);
        user_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        user_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_passFocusGained(evt);
            }
        });
        jPanel2.add(user_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 250, 24));

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setBorder(null);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel2.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 250, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 250, 10));

        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 0, 0));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, 220, 12));

        lbl_pass.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_pass.setForeground(new java.awt.Color(255, 0, 0));
        lbl_pass.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(lbl_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 105, 220, 12));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 440, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        try {
            // TODO add your handling code here
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/ihome","root","");
            String query = "select  Username, Password from users where Username LIKE '%"+txt_user.getText()+"%'";
            PreparedStatement statement = con.prepareStatement(query); 
            ResultSet result = statement.executeQuery();
            if (result.next())
                {   
                    lbl_user.setText("");
                    String dbasePassword=result.getString("Password").toString().trim();
                    String enteredPassword=new String(user_pass.getText().trim());
                    
                    if(dbasePassword.equals(enteredPassword)){
                        lbl_pass.setText("");
                        dispose();
                        Stock stock = new Stock();
                        stock.setVisible(true);
                    }
                    else{
                        lbl_pass.setText("Password is not matching");
                    } 
                }                     
                else
                {                  
                    lbl_user.setText("Usernam is invalid");              
                }                      
                statement.close();
                con.close();
                
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_clsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseEntered
        // TODO add your handling code here:
        btn_cls.setForeground(Color.white);
    }//GEN-LAST:event_btn_clsMouseEntered

    private void btn_clsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseExited
        // TODO add your handling code here:
        btn_cls.setForeground(Color.black);
    }//GEN-LAST:event_btn_clsMouseExited

    private void btn_clsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_clsMousePressed

    private void btn_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseEntered
        // TODO add your handling code here:
        btn_min.setForeground(Color.white);
    }//GEN-LAST:event_btn_minMouseEntered

    private void btn_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseExited
        // TODO add your handling code here:
        btn_min.setForeground(Color.black);
    }//GEN-LAST:event_btn_minMouseExited

    private void btn_minMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMousePressed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minMousePressed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        // TODO add your handling code here:
        btn_login.setBackground(Color.white);
        btn_login.setForeground(Color.black);
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        // TODO add your handling code here:
        btn_login.setBackground(Color.black);
        btn_login.setForeground(Color.white);
    }//GEN-LAST:event_btn_loginMouseExited

    private void txt_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userFocusGained

    private void user_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_passFocusGained
        // TODO add your handling code here:
        user_pass.setText("");
    }//GEN-LAST:event_user_passFocusGained

    private void txt_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMousePressed
        // TODO add your handling code here:
        txt_user.requestFocus();
        txt_user.setText("");
    }//GEN-LAST:event_txt_userMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cls;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel btn_min;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_pass;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt_user;
    private javax.swing.JPasswordField user_pass;
    // End of variables declaration//GEN-END:variables
}
