/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iHome;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ovin Hansaja
 */
public class Supply extends javax.swing.JFrame {

    /**
     * Creates new form Arrived
     */
    public Supply() {
        initComponents();
        Connect();
        Model();
        Color();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel df;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ihome","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Community.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void load()
    {
        int a;
        
        try {
            pst = con.prepareStatement("select * from supply");
            rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            a = rd.getColumnCount();
            df = (DefaultTableModel)tbl_supply.getModel();
            df.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int i=1; i<=a; i++)
                {
                    v2.add(rs.getString("Model"));
                    v2.add(rs.getString("Color"));
                    v2.add(rs.getString("Quentity"));
                    v2.add(rs.getString("Date"));
                }
                df.addRow(v2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Supply.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void Model()
    {
        try {
            pst = con.prepareStatement("select distinct Model from Stock");
            rs = pst.executeQuery();
            
            cmb_model.removeAllItems();
            
            while(rs.next())
                    {
                        cmb_model.addItem(rs.getString("Model"));
                        cmb_model.setSelectedItem("");
                    }
            
        } catch (SQLException ex) {
            Logger.getLogger(Supply.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void Color()
    {
        try {
            pst = con.prepareStatement("select distinct Color from Stock where Model='iPhone 7'");
            rs = pst.executeQuery();
            
            cmb_color.removeAllItems();
            
            while(rs.next())
                    {
                        cmb_color.addItem(rs.getString("Color"));
                        cmb_color.setSelectedItem("");
                    }
            
        } catch (SQLException ex) {
            Logger.getLogger(Supply.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_delivery = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_stock = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_supply = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        btn_community = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_cls = new javax.swing.JLabel();
        btn_min = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_show = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_supply = new javax.swing.JTable();
        txt_quen = new javax.swing.JTextField();
        cmb_model = new javax.swing.JComboBox<>();
        cmb_color = new javax.swing.JComboBox<>();
        lbl_quen = new javax.swing.JLabel();
        lbl_color = new javax.swing.JLabel();
        lbl_model = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_delivery.setBackground(new java.awt.Color(153, 153, 153));
        btn_delivery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deliveryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deliveryMouseExited(evt);
            }
        });
        btn_delivery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/delivered.png"))); // NOI18N
        btn_delivery.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel6.setText("DELIVERY");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_delivery.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_delivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        btn_stock.setBackground(new java.awt.Color(153, 153, 153));
        btn_stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_stockMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_stockMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_stockMouseExited(evt);
            }
        });
        btn_stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/stock.png"))); // NOI18N
        btn_stock.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel1.setText("STOCK");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_stock.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        btn_supply.setBackground(new java.awt.Color(204, 204, 204));
        btn_supply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_supply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supplyMouseExited(evt);
            }
        });
        btn_supply.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/Supply.png"))); // NOI18N
        btn_supply.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel5.setText("SUPPLY");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_supply.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_supply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/iHome-Logo 200x200.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setFont(new java.awt.Font("Century", 2, 18)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, 20));

        btn_community.setBackground(new java.awt.Color(153, 153, 153));
        btn_community.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_community.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_communityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_communityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_communityMouseExited(evt);
            }
        });
        btn_community.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iHome/logos/community.png"))); // NOI18N
        btn_community.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel12.setFont(new java.awt.Font("Stencil", 0, 20)); // NOI18N
        jLabel12.setText("COMMUNITY");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_community.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 140, 24));

        jPanel2.add(btn_community, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cls.setBackground(new java.awt.Color(255, 255, 255));
        btn_cls.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cls.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cls.setText("x");
        btn_cls.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_cls.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_cls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clsMousePressed(evt);
            }
        });
        jPanel4.add(btn_cls, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 20));

        btn_min.setBackground(new java.awt.Color(51, 51, 51));
        btn_min.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_min.setText("-");
        btn_min.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_minMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_minMousePressed(evt);
            }
        });
        jPanel4.add(btn_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 30, 20));

        jLabel7.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 20)); // NOI18N
        jLabel7.setText("The best iPhone collection...");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 250, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("Quentity :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Color :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Model :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        btn_add.setBackground(new java.awt.Color(153, 153, 153));
        btn_add.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btn_add.setText("Add");
        btn_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 100, -1));

        btn_show.setBackground(new java.awt.Color(255, 255, 255));
        btn_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_showMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_showMouseExited(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("MV Boli", 2, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SHOW >>>");

        javax.swing.GroupLayout btn_showLayout = new javax.swing.GroupLayout(btn_show);
        btn_show.setLayout(btn_showLayout);
        btn_showLayout.setHorizontalGroup(
            btn_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        btn_showLayout.setVerticalGroup(
            btn_showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(btn_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 400, 24));

        tbl_supply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model", "Color", "Quentity", "Date"
            }
        ));
        tbl_supply.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tbl_supply);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 740, 360));

        txt_quen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_quen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(txt_quen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 100, -1));

        cmb_model.setEditable(true);
        cmb_model.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Model" }));
        cmb_model.setAutoscrolls(true);
        cmb_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_modelActionPerformed(evt);
            }
        });
        jPanel3.add(cmb_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, -1));

        cmb_color.setEditable(true);
        cmb_color.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cmb_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Color" }));
        cmb_color.setAutoscrolls(true);
        jPanel3.add(cmb_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 200, -1));

        lbl_quen.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_quen.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lbl_quen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 135, 220, 12));

        lbl_color.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_color.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lbl_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 85, 220, 12));

        lbl_model.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_model.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lbl_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 35, 220, 12));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 800, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deliveryMouseEntered
        // TODO add your handling code here:
        btn_delivery.setBackground(Color.white);
    }//GEN-LAST:event_btn_deliveryMouseEntered

    private void btn_deliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deliveryMouseExited
        // TODO add your handling code here:
        btn_delivery.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_deliveryMouseExited

    private void btn_supplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplyMouseEntered
        // TODO add your handling code here:
        btn_supply.setBackground(Color.white);
    }//GEN-LAST:event_btn_supplyMouseEntered

    private void btn_supplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplyMouseExited
        // TODO add your handling code here:
        btn_supply.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_supplyMouseExited

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setForeground(Color.white);
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setForeground(Color.black);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_clsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseEntered
        // TODO add your handling code here:
        btn_cls.setForeground(Color.white);
    }//GEN-LAST:event_btn_clsMouseEntered

    private void btn_clsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMouseExited
        // TODO add your handling code here:
        btn_cls.setForeground(Color.black);
    }//GEN-LAST:event_btn_clsMouseExited

    private void btn_clsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clsMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_clsMousePressed

    private void btn_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseEntered
        // TODO add your handling code here:
        btn_min.setForeground(Color.white);
    }//GEN-LAST:event_btn_minMouseEntered

    private void btn_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMouseExited
        // TODO add your handling code here:
        btn_min.setForeground(Color.black);
    }//GEN-LAST:event_btn_minMouseExited

    private void btn_minMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minMousePressed
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minMousePressed

    private void btn_stockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseEntered
        // TODO add your handling code here:
        btn_stock.setBackground(Color.white);
    }//GEN-LAST:event_btn_stockMouseEntered

    private void btn_stockMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseExited
        // TODO add your handling code here:
        btn_stock.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_stockMouseExited

    private void btn_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_stockMouseClicked
        // TODO add your handling code here:
        dispose();
        Stock stock = new Stock();
        stock.setVisible(true);
    }//GEN-LAST:event_btn_stockMouseClicked

    private void btn_deliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deliveryMouseClicked
        // TODO add your handling code here:
        dispose();
        Delivery delivery = new Delivery();
        delivery.setVisible(true);
    }//GEN-LAST:event_btn_deliveryMouseClicked

    private void btn_communityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_communityMouseClicked
        // TODO add your handling code here:
        dispose();
        Community community = new Community();
        community.setVisible(true);
    }//GEN-LAST:event_btn_communityMouseClicked

    private void btn_communityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_communityMouseEntered
        // TODO add your handling code here:
        btn_community.setBackground(Color.white);
    }//GEN-LAST:event_btn_communityMouseEntered

    private void btn_communityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_communityMouseExited
        // TODO add your handling code here:
        btn_community.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_communityMouseExited

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        // TODO add your handling code here:
        btn_add.setBackground(Color.white);
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        // TODO add your handling code here:
        btn_add.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_showMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showMouseEntered
        // TODO add your handling code here:
        btn_show.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btn_showMouseEntered

    private void btn_showMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showMouseExited
        // TODO add your handling code here:
        btn_show.setBackground(Color.white);
    }//GEN-LAST:event_btn_showMouseExited

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            // TODO add your handling code here:
            String model = cmb_model.getSelectedItem().toString();
            String color = cmb_color.getSelectedItem().toString();
            String quentity = txt_quen.getText();
            int q1 = Integer.parseInt(quentity);
            
            if(model.equals(""))
            {
                lbl_model.setText("Select a Model");
            }
            else
            {
                lbl_model.setText("");
                
                if(color.equals(""))
                {
                    lbl_color.setText("Select a Color");
                }
                else
                {
                    lbl_color.setText("");
                    
                    if(quentity.equals(""))
                    {
                       lbl_quen.setText("Quentity cannot be empty"); 
                    }
                    else if(!quentity.matches("^[0-9]*$"))
                    {
                        lbl_quen.setText("Quentity should be numeric");
                    }
                    else
                    {
                        lbl_quen.setText("");
                        
                        String query = "Insert into supply(Model,Color,Quentity) values('"+model+"','"+color+"','"+quentity+"')";
                        pst.executeUpdate(query);
                        JOptionPane.showMessageDialog(this, "Supply Added");
                        
                        String query1 = "Select Quentity from stock where Model = '"+model+"' && Color = '"+color+"'";
                        rs = pst.executeQuery(query1);
                        
                        while(rs.next()){
                            String q2 = rs.getString("Quentity");
                            int q3 = Integer.parseInt(q2);
                            int q4 = q3+q1;
                            String q5 = Integer.toString(q4);

                            String query2 = "Update stock set Quentity = '"+q5+"' where Model = '"+model+"' && Color = '"+color+"'";
                            pst.executeUpdate(query2);
                        }
                        cmb_model.setSelectedIndex(0);
                        cmb_color.setSelectedIndex(0);
                        txt_quen.setText("");
                        cmb_model.requestFocus();
                    }
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Supply.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showMouseClicked
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_btn_showMouseClicked

    private void cmb_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_modelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel btn_cls;
    private javax.swing.JPanel btn_community;
    private javax.swing.JPanel btn_delivery;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_min;
    private javax.swing.JPanel btn_show;
    private javax.swing.JPanel btn_stock;
    private javax.swing.JPanel btn_supply;
    private javax.swing.JComboBox<String> cmb_color;
    private javax.swing.JComboBox<String> cmb_model;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_model;
    private javax.swing.JLabel lbl_quen;
    private javax.swing.JTable tbl_supply;
    private javax.swing.JTextField txt_quen;
    // End of variables declaration//GEN-END:variables
}
